---
title: "EDA & 피처엔지니어링"
date: "2022-10-12"
author: "김민영"
---



# 1. 패키지 및 데이터 로드

```{r 패키지}
suppressPackageStartupMessages({
  require(DataExplorer)
  require(skimr)
  require(data.table)
  require(dplyr)
  require(magrittr)
  require(googledrive)
  require(ggplot2)
  require(lubridate)
  require(tsibble)
  require(stringr)
  require(mice)
  require(VIM)
  require(fastDummies)
  require(caret)
 
})

#options(scipen=999)
```

```{r 데이터 로드}
dir = tempfile(fileext = ".csv")
drive_download(as_id("-----------------------------"), path = dir, overwrite = TRUE)
dt = fread(dir)

```

```{r}
drive_download(as_id("-----------------------------"), path = dir, overwrite = TRUE)
user = fread(dir,
    col.names = c('신청서번호', '유저번호','생년월일','성별','한도조회_당시_시간',
    '한도조회_당시_신용점수','연소득','근로형태','입사연월','고용형태',
    '주거소유형태','대출희망금액','대출목적','개인회생자_여부','개인회생자납입_여부',
    '기대출수','기대출금액'))

drive_download(as_id("-----------------------------"), path = dir, overwrite = TRUE)
loan = fread(dir, 
    col.names = c('신청서번호','한도조회일시','금융사번호','상품번호','승인한도',
    '승인금리','신청_여부'))
```

```{R 서버}
getwd()
setwd("C:/Users/USER/Downloads")
dt = fread("DT.csv")
user = fread("user_spec.csv",
    col.names = c('신청서번호', '유저번호','생년월일','성별','한도조회_당시_시간',
    '한도조회_당시_신용점수','연소득','근로형태','입사연월','고용형태',
    '주거소유형태','대출희망금액','대출목적','개인회생자_여부','개인회생자납입_여부',
    '기대출수','기대출금액'))
loan = fread("loan_result.csv", 
    col.names = c('신청서번호','한도조회일시','금융사번호','상품번호','승인한도',
    '승인금리','신청_여부'))


```


# 2.범주형 변수
## 2-1. 고객이 직접입력하는 변수  
### 2-1-1. 결측치 없는 변수
```{r Cat vars}
dt_cat = dt %>% select(신청서번호, 성별, 근로형태, 고용형태, 주거소유형태, 대출목적 ,신청_여부)
dt_cat %<>% mutate(근로형태 = case_when(근로형태 == "EARNEDINCOME" ~ "4대직장",
    근로형태 == "EARNEDINCOME2" ~ "직장",
    근로형태 == "PRIVATEBUSINESS" ~ "개인사업",
    근로형태 == "PRACTITIONER" ~ "전문직",
    근로형태 == "FREELANCER" ~ "프리랜서",
    TRUE ~ "기타소득"))
```

```{r 근로형태, echo=FALSE}
table(dt_cat$근로형태) %>% prop.table()*100
```


```{r 고용형태}
table(dt_cat$고용형태) %>% prop.table()*100
```

```{r 주거소유형태}
table(dt_cat$주거소유형태) %>% prop.table()*100
```

```{r 대출목적}
#table(dt_cat$대출목적) %>% prop.table()*100

dt_cat %<>% mutate(대출목적 =  str_replace(대출목적, "BUSINESS" ,"사업자금") ,
                  대출목적= str_replace(대출목적, "BUYCAR" ,"자동차구입"),
                  대출목적= str_replace(대출목적, "BUYHOUSE" , "주택구입"),
                  대출목적= str_replace(대출목적,  "ETC" , "기타"),
                  대출목적= str_replace(대출목적, "HOUSEDEPOSIT" , "전월세보증금"),
                  대출목적= str_replace(대출목적, "INVEST" , "투자"),
                  대출목적= str_replace(대출목적,"LIVING" ,"생활비"),
                  대출목적= str_replace(대출목적, "SWITCHLOAN" , "대환대출")
                  )

#dt_cat$대출목적 %>% table %>% prop.table*100

```

```{r dt_cat}

dt_cat_filter = dt_cat %>% filter(!is.na(신청_여부), !is.na(성별))

plot_bar(dt_cat_filter, by='신청_여부')
```

### 2-1-2. 
####1) 결측치 있는 변수(개인회생여부, 개인회생납입여무)
```{r }

#개인회생자_na = dt %>% filter(is.na(개인회생자_여부))
#개인회생자_cmp = dt %>% filter(!is.na(개인회생자_여부))

dt %>% mutate(개인회생 = case_when(개인회생자_여부==0 ~ "비인가",
	개인회생자_여부 ==1 &  개인회생자납입_여부 == 0 ~ "납입중",
	개인회생자_여부 ==1 &  개인회생자납입_여부 == 1 ~ "납입완료",
	TRUE ~ "알수없음" )) ->tmp

dt_cat[,'개인회생'] = tmp[,'개인회생']

#tmp$개인회생%>% is.na %>% sum

#tmp$개인회생%>% table %>% prop.table*100

#개인회생자_na$신청_여부 %>% table 
#개인회생자_cmp$신청_여부 %>% table 

```
~~일단 넣어보고 -> 제거 결정??~~
논거1. 결측치 비율이 많음
논거2.  인사이트에 도움 안됨

#### 2) 성별(생년월일과 묶어서)

```{r 성별, echo= TRUE}
성별_na = dt %>% filter(is.na(성별))
#생년월일_na = dt %>% filter(is.na(생년월일))
성별_na %>% filter(!is.na(생년월일)) #성별이 결측이면 생년월일도 결측이다.
#생년월일_na %>% filter(!is.na(성별)) # 역시 확인 가능
성별_na %>% head
# 유저 테이블에서 찾아봐야함-> 버릴 수 없음. imputation 해야 함.
```

```{r 나이, echo = TRUE}
dt %>% select(신청서번호,한도조회_당시_시간.x ,생년월일, 신청_여부) -> tmp

tmp %>% 
  mutate(출생연도 = year(parse_date_time(생년월일, orders="y")),
               당시연도 = year(한도조회_당시_시간.x)) ->tmp2

cmp = tmp2 %>%
  mutate(나이 = as.duration( 당시연도 - 출생연도) %>% as.numeric()
         ) 
#최종
dt_나이 = cmp %>% select(신청서번호,나이)
```

# 3. 연속형 변수
## 3-1. 입사연월 -> 근속기간
```{r }

dt_num = dt %>% select(한도조회_당시_시간.x, 유저번호, 신청서번호, 대출희망금액,연소득,
                       한도조회_당시_신용점수,입사연월,기대출수,기대출금액, 신청_여부)
#월까지 추출
dt_num %>% mutate(입사연월 = parse_date_time(substr(입사연월, 1,6), orders="ym"),
                  당시연월 =parse_date_time(yearmonth(한도조회_당시_시간.x), orders="ym"),
                  근속기간 = ((year(당시연월) * 12 + month(당시연월)) - (year(입사연월) * 12 + month(입사연월)))/12
                  ) -> num_tmp
#확인
#lot_missing(num_tmp)

```
## 3-2. 분포확인
```{r }
#dt_num = dt %>% select(한도조회_당시_시간.x, 유저번호, 신청서번호, 대출희망금액,연소득,
#                       한도조회_당시_신용점수,입사연월,기대출수,기대출금액)

#dt_num2 = dt_num %>% select(신청서번호, 대출희망금액,연소득, 한도조회_당시_신용점수,기대출수,기대출금액,신청_여부)


#dt_num %>% summary
#대출희망금액, 연소득, 기대출금액 max값 큼
#신용점수, 근속연수, na데이터 특징 궁금
```


# 4. 최종 데이터셋 병합
```{r 최종 데이터셋 생성}

dt %>% select(신청서번호, 유저번호, 금융사번호, 상품번호, 승인한도, 
              승인금리, 성별, 연소득,한도조회_당시_신용점수, 
              대출희망금액, 기대출금액,신청_여부) -> dt2

dt_cat %>% select(-신청서번호, -성별,-신청_여부) -> dt_cat2
dt_나이 %>% select(- 신청서번호) -> dt_나이2
num_tmp %>% select(근속기간) -> num_tmp2

#병합
DT = cbind(dt2,dt_cat2,dt_나이2,num_tmp2 )
DT %<>% rename(신용점수 = 한도조회_당시_신용점수) 

```

## 4-1. 결측치 처리
```{r 나이, 성별 imputation}
plot_missing(DT)
```
### 4-1-1.결측값이 존재하는 변수
```{R 나이&성별}
#step1.분포 확인(사실상 아웃라이어 존재할 수 없음)
DT %>% select(나이) 

skim(DT$나이)
hist(DT$나이)

#write.csv(DT, "DT.csv", row.names=FALSE)
```

```{r 근속기간}
#DT %>% filter(is.na(근속기간))
#skim(DT$근속기간)

#DT %>% arrange(근속기간) %>% head(30) %>% View
#음수값 확인
#tmp = cbind( DT, dt[,'입사연월']) 
#tmp %>% arrange(근속기간) %>%filter(근속기간<0) # 결측치 처리
DT[근속기간<0 , 근속기간 :=NA]

#tmp %>% arrange(근속기간) %>%head(250) %>% View
#tmp %>% filter (근속기간 ==1) %>%head(250) %>% View


#tmp %>% select(근속기간, 나이) ->tmp2

#plot(tmp2$근속기간, tmp2$나이)

DT[근속기간>나이 , 근속기간 :=NA]


#tmp %>% arrange(근속기간) %>%filter(근속기간>80)

#분포를 헤치지 않는 선에서
#공무원 정년 퇴직 나이 기준값과같음  생각해서 0.999
out = quantile(tmp$근속기간, c(0.999), na.rm = TRUE)
DT[근속기간>out , 근속기간 :=NA]
```

```{r 한도조회 신용점수}
#그대로 감 
#summary(DT$한도조회_신용점수)

```

```{R 기대출 금액}

#DT$기대출금액 %>% class
 
#DT$기대출금액 %>% summary
#분포를 헤치지 않는 선에서 0.999값으로 
out_대출 = quantile(DT$기대출금액, c(0.999), na.rm = TRUE)
DT[기대출금액>out_대출 , 기대출금액 :=NA]

```
### 4-1-2.결측값이 존재하지 않는 변수

```{r 대출희망금액}
#T$대출희망금액 %>% summary
#분포를 헤치지 않는 선에서
out_희망금액 = quantile(DT$대출희망금액, c(0.999), na.rm = TRUE)
DT[대출희망금액>out_희망금액 , 대출희망금액 :=NA]

#대출희망금액 ==0 결측치로 처리(앱 내에서 0으로 하면 안넘어감)
DT[대출희망금액 == 0 , 대출희망금액 :=NA]

```


```{r 승인한도}
out_승인한도 = quantile(DT$승인한도, c(0.999), na.rm = TRUE)
DT[승인한도>out_승인한도 , 승인한도 :=NA]
#summary(DT$승인한도)
# DT$승인금리 %>% summary 이상없음 

```


```{r 연소득}
#summary(DT$연소득)
out_연소득 = quantile(DT$연소득, c(0.999), na.rm = TRUE)
DT[연소득>out_연소득 , 연소득 :=NA]
#맥스 
#DT %>% filter( is.na(연소득))   
```


```{r 기대출금액}
# 직접 입력하는거 아님. -> 그냥 사용

#DT %>% filter(is.na(기대출금액))
#DT$기대출금액 %>% summary

```

```{r missing plot}
plot_missing(DT)
```

ls()
write.csv(DT, "DT_CMP.csv", row.names=FALSE)
getwd()

## 4-2 결측치 대체
```{r}
#step1 큰 수 바꾸기
DT %<>% mutate(승인한도 =승인한도/1000000 ,
              연소득 = 연소득/1000000,
              대출희망금액 = 대출희망금액/1000000,
              기대출금액 = 기대출금액/1000000) 
```

```{r 성별}
#1. 성별- 최빈값 대체
#함수생성
#mode= function(x){
#   which.max(table(x)) %>% names
#}

#DT %>% mutate(성별 = ifelse(is.na(성별), mode(DT$성별), DT$성별 )) %>% sum(is.na(DT$성별)) 
#DT$성별 %>% table %>% prop.table*100
DT[is.na(성별), "성별"] <-1
```

```{r 나이, 근속, 신용}
#2. 나이
#plot_qq(DT$나이)
#hist(DT$나이)
#qqnorm(DT$나이)
#skim(DT$나이)
DT[is.na(나이), "나이"] <- mean(DT$나이, na.rm=TRUE) 

DT %>% select(나이) %>%
  mutate(나이대 = case_when(나이<29 ~ "20대이하",
                          나이>=30 & 나이<39 ~ "30대",
                          나이>=40 & 나이 <49 ~ "40대",
                          나이>=50 & 나이<59 ~ "50대",
                          나이 >=60 & 나이< 69 ~ "60대",
                          TRUE~ "기타")) -> tmp_나이

#DT$나이 %>% summary

DT[,'나이대'] = tmp_나이$나이대
#근속기간


DT %>% group_by(나이대) %>%
  summarise(근속기간_평균 = mean(근속기간, na.rm= TRUE),
            근속기간_중앙 = median(근속기간, na.rm=TRUE))

#DT %>% mutate(근속기간 = case_when( is.na(근속기간) & 나이대 == "20대이하" ~ 0.8333333,
#                                is.na(근속기간) & 나이대 == "30대" ~ 2.0000000,
#                                is.na(근속기간) & 나이대 == "40대" ~ 3.0000000,	
#                                is.na(근속기간) & 나이대 == "50대" ~ 2.9166667,	
#                                is.na(근속기간) & 나이대 == "60대" ~ 2.2500000,
#                                is.na(근속기간) & 나이대 == "기타" ~ 2.1666667,
#                                TRUE ~ 근속기간
#                                )) -> tmp_근속기간
DT %<>% mutate(근속기간 = case_when( is.na(근속기간) & 나이대 == "20대이하" ~ 0.8333333,
                                is.na(근속기간) & 나이대 == "30대" ~ 2.0000000,
                                is.na(근속기간) & 나이대 == "40대" ~ 3.0000000,	
                                is.na(근속기간) & 나이대 == "50대" ~ 2.9166667,	
                                is.na(근속기간) & 나이대 == "60대" ~ 2.2500000,
                                is.na(근속기간) & 나이대 == "기타" ~ 2.1666667,
                                TRUE ~ 근속기간
                                ))


#DT %>% filter(  is.na(근속기간) & 나이대 == "20대이하") %>% head

#tmp_근속기간$근속기간 %>% is.na %>% sum
#skim(tmp_근속기간$근속기간)
DT %<>% select(-나이대)

```

plot_missing(DT)


```{r 연소득, 대출희망금액, 신용점수}

#skim(DT$연소득) # 중앙값 대체 
#skim(DT$대출희망금액)
#skim(DT$한도조회_신용점수)
DT[is.na(연소득), "연소득"] <-median(DT$연소득, na.rm=TRUE)
DT[is.na(대출희망금액), "대출희망금액" ] <-median(DT$대출희망금액, na.rm=TRUE)
DT[is.na(신용점수), "신용점수"] <- median(DT$신용점수, na.rm=TRUE)
DT[is.na(승인한도), "승인한도"]   <- median(DT$승인한도, na.rm= TRUE)
#기대출금액
DT[is.na(기대출금액), 기대출금액 := 0]
```

```{r}
#파라미터
#set.seed(5543)
#seed=5543
#m= 5

#타겟제외
#Classification and regression trees
#imp_cart = mice(tmp_imp,
#           m= m,
#           method ="cart" ,
#           seed=5543)

#plot(imp)
#stripplot(imp, pch = 20 , cex= 1.2)
#imp_cmp = complete(imp_cart, 1)

```


# 5. 파생피처
```{r }
#개인회생. 나이, 근속연수는 데이터 합치기 단계에서 함
DT %<>% mutate( 기대출과다_여부 = ifelse(기대출금액>=연소득,1,0),
	기대출_여부 = ifelse(기대출금액 == 0 , 0 , 1))

```

# 7 데이터 인코딩
```{r}
#step1. 범주 개수 조정
#근로형태 - 4대직장, 기타
DT %<>%mutate(근로형태 = ifelse(근로형태 =="4대직장", "4대직장","기타"))
       
#고용형태 - 정규직. 기타
DT %<>%mutate(고용형태 = ifelse(고용형태 =="정규직", "정규직","기타"))
#주거소유형태 - 전월세,자가,기타

DT %<>% mutate(주거소유형태 = case_when(주거소유형태== "전월세"~ "전월세",
                                 주거소유형태 =="자가"~"자가",
                                 TRUE ~ "기타"))

#대출목적 - 생활비, 대환대출, 기타
DT %<>% mutate(대출목적 = case_when(대출목적== "생활비"~ "생활비",
                                대출목적 =="대환대출"~"대환대출",
                                TRUE ~ "기타"))
```



# 6. 피처제거 (상관관계보고)
```{r 연속형}
# DT %<>% rename(신용점수 = 한도조회_신용점수)
DT %>% select_if(is.numeric) -> dt_num
plot_correlation(na.omit(dt_num[,-c(1:4,7,12,15:16)])) # 명목형 삭제

```

```{r 범주형}

DT%>% select_if(is.character) -> dt_cha
dt_cha  %>% names
DT %>% select(성별,기대출과다_여부,기대출_여부,신청_여부) ->tmp
cmp = cbind(dt_cha,tmp)
chisq.test(xtabs(신청_여부~성별, data=cmp))


cmp %<>%mutate(근로형태 = ifelse(근로형태 =="4대직장", 1,0))
chisq.test(xtabs(신청_여부~근로형태, data=cmp))


cmp$근로형태 %>% summary
#cmp %>% str

cmp %<>%mutate(고용형태 = ifelse(고용형태 =="정규직", 1,0))
chisq.test(xtabs(신청_여부~고용형태, data=cmp))


cmp %<>%mutate(주거소유형태 = case_when(주거소유형태 =="자가"~ 0,
                                  주거소유형태=="전월세"~1,
                                  TRUE ~2))
chisq.test(xtabs(신청_여부~주거소유형태, data=cmp))


cmp %<>%mutate(대출목적 = case_when(대출목적 =="생활비"~ 0,
                                  대출목적=="대환대출"~1,
                                  TRUE ~2))
chisq.test(xtabs(신청_여부~대출목적, data=cmp))


cmp %<>%mutate(개인회생 = case_when(개인회생 =="납입완료"~ 0,
                                개인회생=="납입중"~1,
                                개인회생=="비인가"~1,
                                TRUE ~3))
chisq.test(xtabs(신청_여부~개인회생, data=cmp))


chisq.test(xtabs(신청_여부~기대출과다_여부, data=cmp))
chisq.test(xtabs(신청_여부~기대출_여부, data=cmp))




xtabs(성별~신청_여부, data=cmp)

#cmp %>% count(근로형태, wt = 신청_여부) 
#cmp %>% count(개인회생, wt = 신청_여부) 

```

```{r}
DT %>% plot_missing()
```


```{r}
#step1. 원핫인코딩
DT = dummy_cols(DT, remove_selected_columns = T)

#step2. 스케일링
#함수정의
minMax = function(x){
  (x-min(x)) / (max(x)-min(x))
}



DT %>% select(금융사번호, 상품번호, 승인한도, 승인금리, 연소득, 
              신용점수,대출희망금액,기대출금액,나이,근속기간) -> DT_num

DT_num = minMax(DT_num) 


DT %>% select(-금융사번호, -상품번호, -승인한도, -승인금리, -연소득, 
              -신용점수,-대출희망금액,-기대출금액,-나이,-근속기간) -> DT_cat

final = cbind(DT_cat,DT_num)
#final %>% head

```



# 8. 테스트 데이터 분리
```{r}
train = final %>% filter(!is.na(신청_여부))
test = final%>% filter(is.na(신청_여부))

```


# 9. 샘플링
```{R SMOTE}
#install.packages("remotes")
#remotes::install_github("cran/DMwR")
#step1. SMOTE
train[,'신청_여부'] = factor(train$신청_여부)
#SMT = DMwR::SMOTE(신청_여부~., train)

#down
smp = caret::downSample(x = subset(train, select=-신청_여부), 
                        y = train$신청_여부,
                        yname = "신청_여부")
smp$신청_여부 %>% table



lr_smp = caret::downSample(x = subset(train, select=-신청_여부), 
                        y = train$신청_여부,
                        yname = "신청_여부")
#plot_bar(smp$신청_여부)

```


#저장
```{r}
getwd()
write.csv(smp, "smp.csv", row.names=FALSE)
write.csv(train, "train.csv", row.names=FALSE)
write.csv(test, "test.csv", row.names=FALSE)

```


